services:
    keycloak:
        image: quay.io/keycloak/keycloak:${KEYCLOAK_IMAGE_TAG:-26.0.6}
        container_name: keycloak
        command: start-dev
        init: true
        ports:
            - "8080:8080"
        volumes:
            - ./themes:/opt/keycloak/themes
            - ./providers:/opt/keycloak/providers
            - keycloak-data:/opt/keycloak/data
        env_file:
            - keycloak.env
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: keycloak-mysql
        restart: always
        env_file:
            - keycloak.env
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    keycloak-data:
    mysql-data:
